Desktop version
Tshobohwa/Portfolio pull request #5
Opened 2023-01-26 18:32 UTC by Tshobohwa

# FEATURES ADDED
-footer form
-desktop version

2023-01-26 19:27 UTC, Tshobohwa commented
# PARTNER CHALLENGE.
Dear reviewer, please consider the fact that unfortunately, I did not have any available partner this week, and consequently, I completed alone this activity.

2023-01-26 19:50 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Tshobohwa, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Correct use of GitHub flow. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-26 19:50 UTC, leonardodiasb commented on index.html
> +        </ul>
- [ ] Your navbar is good and very similar to the Figma template. But kindly reduce the font-size of the items to match the Figma template and look more professional.
 - [ ] Also please use the proper id of the sections in the `href` attribute of the nav items to redirect the user to the correct part of the page. Currently, this is making the user leave the page and this is not a good UX.

2023-01-26 19:50 UTC, leonardodiasb commented on style.css
> +  }
- [ ] Kindly reduce the padding left and right to make your page looks more like the desktop version of the Figma template. There is a lot of whitespace on the sides of this section.
 - Your version:
 - 
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/61919617/214934218-69913ba2-a702-4596-a57a-92864311b846.png">

 - Figma template:
 - 
<img width="984" alt="image" src="https://user-images.githubusercontent.com/61919617/214934283-2a944fd0-5c3a-408f-b778-e1fbc6c1d615.png">

2023-01-26 19:50 UTC, leonardodiasb commented on index.html
> +              </ul>
- [ ] Kindly reduce the font-size of the technologies list in all the cards to match the Figma template. On the template, the font-size is smaller than the rest of the content of the card.
 - Your design:
 - 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/61919617/214935360-71277222-1388-4c52-816f-7a0e7d4e50c9.png">

 - Figma template:
 - 
<img width="793" alt="image" src="https://user-images.githubusercontent.com/61919617/214935413-1bba1f59-1544-4353-a032-92fb341d1267.png">

2023-01-26 20:09 UTC, AbayomiOlaoye requested changes
## STATUS 🔴 

Hi @Tshobohwa 👍 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![invalid](https://user-images.githubusercontent.com/99715640/211858554-39090b6b-2f0f-45dd-b5e0-8fb805e56431.gif)

## Invalid Code Review Request

You have submitted a pull request with the wrong repository address. Kindly consider checking again from your end and submit the appropriate link. You submitted a link to your `Desktop verison` instead of the `Contact section`.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-27 11:45 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @Tshobohwa , 

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 06:54 UTC, merged